import * as React from "react";
const ESP = (props) => (
  <svg
    viewBox="0 0 400 400"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <defs>
      <g id="circuit">
        <path
          d="M95 30 l -14 0 M 95 50 l -14 0 M 95 70 l -14 0 M5 30 l 14 0 M 5 50 l 14 0 M 5 70 l 14 0 M30 5 l 0 14 M 50 5 l 0 14 M 70 5 l 0 14 M30 95 l 0 -14 M 50 95 l 0 -14 M 70 95 l 0 -14"
          fill="transparent"
          stroke-width="12"
          stroke-linejoin="round"
          stroke-linecap="round"
        />
        <path
          d="M20 20 l 60 0 l 0 60 l -60 0 l 0 -60"
          fill="transparent"
          stroke-width="12"
          stroke-linejoin="round"
          stroke-linecap="round"
        />
        <path
          d="M95 30 l -14 0 M 95 50 l -14 0 M 95 70 l -14 0 M5 30 l 14 0 M 5 50 l 14 0 M 5 70 l 14 0 M30 5 l 0 14 M 50 5 l 0 14 M 70 5 l 0 14 M30 95 l 0 -14 M 50 95 l 0 -14 M 70 95 l 0 -14"
          fill="transparent"
          stroke="#fff"
          stroke-width="5"
          stroke-linejoin="round"
          stroke-linecap="round"
        />
        <path
          d="M20 20 l 60 0 l 0 60 l -60 0 l 0 -60"
          stroke="#fff"
          stroke-width="5"
          stroke-linejoin="round"
          stroke-linecap="round"
        />
      </g>
    </defs>
    <g>
      <circle id="background" stroke="transparent" cx="200" cy="200" r="200" />
    </g>
    <rect
      x="105"
      y="60"
      height="275"
      width="190"
      fill="transparent"
      stroke-width="12"
      stroke-linejoin="round"
      stroke-linecap="round"
    />
    <rect
      x="105"
      y="60"
      height="275"
      width="190"
      fill="transparent"
      stroke="#fff"
      stroke-width="5"
      stroke-linejoin="round"
      stroke-linecap="round"
    />
    <circle
      cx="200"
      cy="125"
      r="35"
      fill="transparent"
      stroke-width="12"
      stroke-linejoin="round"
      stroke-linecap="round"
    />
    <circle
      cx="200"
      cy="125"
      r="7"
      fill="transparent"
      stroke-width="12"
      stroke-linejoin="round"
      stroke-linecap="round"
    />
    <circle
      cx="200"
      cy="125"
      r="35"
      fill="transparent"
      stroke="#fff"
      stroke-width="5"
      stroke-linejoin="round"
      stroke-linecap="round"
    />
    <circle
      cx="200"
      cy="125"
      r="7"
      fill="transparent"
      stroke="#fff"
      stroke-width="5"
      stroke-linejoin="round"
      stroke-linecap="round"
    />
    <circle
      cx="130"
      cy="90"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke-width="12"
    />
    <circle
      cx="130"
      cy="90"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke="#fff"
      stroke-width="5"
    />
    <circle
      cx="270"
      cy="90"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke-width="12"
    />
    <circle
      cx="270"
      cy="90"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke="#fff"
      stroke-width="5"
    />
    <circle
      cx="130"
      cy="120"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke-width="12"
    />
    <circle
      cx="130"
      cy="120"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke="#fff"
      stroke-width="5"
    />
    <circle
      cx="270"
      cy="120"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke-width="12"
    />
    <circle
      cx="270"
      cy="120"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke="#fff"
      stroke-width="5"
    />
    <circle
      cx="130"
      cy="150"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke-width="12"
    />
    <circle
      cx="130"
      cy="150"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke="#fff"
      stroke-width="5"
    />
    <circle
      cx="270"
      cy="150"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke-width="12"
    />
    <circle
      cx="270"
      cy="150"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke="#fff"
      stroke-width="5"
    />
    <circle
      cx="130"
      cy="180"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke-width="12"
    />
    <circle
      cx="130"
      cy="180"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke="#fff"
      stroke-width="5"
    />
    <circle
      cx="270"
      cy="180"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke-width="12"
    />
    <circle
      cx="270"
      cy="180"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke="#fff"
      stroke-width="5"
    />
    <circle
      cx="130"
      cy="210"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke-width="12"
    />
    <circle
      cx="130"
      cy="210"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke="#fff"
      stroke-width="5"
    />
    <circle
      cx="270"
      cy="210"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke-width="12"
    />
    <circle
      cx="270"
      cy="210"
      r="1"
      fill="transparent"
      stroke-linejoin="round"
      stroke-linecap="round"
      stroke="#fff"
      stroke-width="5"
    />
    <use href="#circuit" x="150" y="210" fill="transparent"/>
  </svg>
);
export default ESP;
